spring:
  datasource:
    url: jdbc:sqlserver://192.168.23.3:1433;databaseName=BIZ_Business
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: P@ssw0rd
    tomcat:
      default-auto-commit: false
      default-read-only: false
      max-active: 100
      max-idle: 10
      max-wait: 10000
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 500
      default-transaction-isolation: 1
      log-abandoned: true
      remove-abandoned-on-maintenance: true
      remove-abandoned-timeout: 5
      test-while-idle: true
  rabbitmq:
    host: 192.168.20.59
    port: 5672
    username: admin
    password: admin
      
server:
  port: 9010
eureka:
  instance:
      hostname: 192.168.20.59
  client:
    eureka-server-port: 9080
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/

management:
  security:
    enabled: false
  
      
